# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: CI/CD Pipeline for iOS Project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - development

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
        
    - name: Update RubyGems
      run: gem update --system 3.2.3


    - name: Install dependencies
      run: |
        sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
        gem install bundler
        bundle install

    - name: Run tests
      run: |
        xcodebuild test -workspace LJNetworkLayer.xcworkspace -scheme YourScheme -destination 'platform=iOS Simulator,name=iPhone 12,OS=latest'

    - name: Build the project
      run: |
        xcodebuild build -workspace LJNetworkLayer.xcworkspace -scheme YourScheme -configuration Release -sdk iphoneos

